CREATE DATABASE RRS;
USE RRS;
CREATE TABLE POST(
	POST_CD      BIGINT PRIMARY KEY AUTO_INCREMENT,
	POST_NM      VARCHAR(20),
	TITLE        VARCHAR(50),
	SORT         VARCHAR(20),
	LOCATION     VARCHAR(1000),
	PHOTO        VARCHAR(200),
	CONTENT      VARCHAR(1000),
	RUNNING_TIME VARCHAR(200) ,
	UPLOAD_DT    TIMESTAMP
);


CREATE TABLE MEMBER(
	MEMBER_ID      VARCHAR(100) PRIMARY KEY,
	PASSWD         VARCHAR(100),
	AGE            INT,
	EMAIL          VARCHAR(50),
	ADDRESS        VARCHAR(20),
	PROFILE        VARCHAR(200),
	AGREE_YN       CHAR(1),
	AGREE_EMAIL_YN CHAR(1)
);

CREATE TABLE COMMENT(
	POST_CD       BIGINT,
    POST_NM       VARCHAR(20),
    MEMBER_ID     VARCHAR(100),
    PROFILE       VARCHAR(200),
    REVIEW        VARCHAR(200),
    RATING        INT,
    REVIEW_LIKE   BIGINT,
    UPLOAD_DT     TIMESTAMP
);

CREATE TABLE BOOKMARK(
	MEMBER_ID VARCHAR(100),
	POST_CD   BIGINT,
	POST_NM   VARCHAR,
	REG_DT    TIMESTAMP
);