CREATE DATABASE PRACTICE;
USE PRACTICE;
CREATE TABLE COL(
	COL1 INT ,
	COL2 INT
);

INSERT INTO COL VALUES(10, 5);
INSERT INTO COL VALUES(20, NULL);
INSERT INTO COL VALUES(NULL,15);

SELECT SUM(COL1)
FROM   COL;

SELECT SUM(COL1), SUM(COL2)
FROM   COL 
WHERE  COL1 > 10;

SELECT SUM(COL1)
FROM   COL 
WHERE  COL2 > 0;

SELECT SUM(COL1), SUM(COL2)
FROM   COL 
WHERE  COL2 > 5;

SELECT SUM(COL1), SUM(COL2)
FROM   COL
WHERE  COL2 IS NOT NULL;